version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.postgres_infrax:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    volumes:
      - ./.redis_infrax:/var/lib/redis
    ports:
      - 6379:6379
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  default:
    driver: bridge
