version: "3"
services:
  postgres:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./.postgres_infrax:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - backend
  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - ./.redis_infrax:/var/lib/redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:4000"
    networks:
      - backend
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/usr/src/app
networks:
  backend:
    driver: bridge
